'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class BallotEntry

    '''<summary>
    '''UpdatePanel_Main control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel_Main As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''CollapsiblePanelExtender_AssignmentInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CollapsiblePanelExtender_AssignmentInfo As Global.AjaxControlToolkit.CollapsiblePanelExtender

    '''<summary>
    '''pnlAssignmentInfo_Title control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlAssignmentInfo_Title As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''imgArrows_AssignmentInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgArrows_AssignmentInfo As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''lblAssignmentInfo_title control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAssignmentInfo_title As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnlAssignmentInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlAssignmentInfo As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCompanyName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCompanyName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblFirstPerformanceDateTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFirstPerformanceDateTime As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblLastPerformanceDateTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLastPerformanceDateTime As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblFullname control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFullname As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCompanyAdjudication control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCompanyAdjudication As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnlStart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlStart As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''CollapsiblePanelExtender_CommonQuestions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CollapsiblePanelExtender_CommonQuestions As Global.AjaxControlToolkit.CollapsiblePanelExtender

    '''<summary>
    '''pnlCommonQuestions_Title control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlCommonQuestions_Title As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''imgArrows_CommonQuestions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgArrows_CommonQuestions As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''lblCommonQuestions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCommonQuestions As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnlCommonQuestions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlCommonQuestions As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblDaysToWaitForScoring control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDaysToWaitForScoring As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblMaxShowsPerAdjudicator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMaxShowsPerAdjudicator As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTitlePerformance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTitlePerformance As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtProductionDateAdjudicated_Planned control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtProductionDateAdjudicated_Planned As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''CalendarExtender_txtProductionDateAdjudicated_Planned control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CalendarExtender_txtProductionDateAdjudicated_Planned As Global.AjaxControlToolkit.CalendarExtender

    '''<summary>
    '''imgCalendarIcon_txtProductionDateAdjudicated_Planned control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgCalendarIcon_txtProductionDateAdjudicated_Planned As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''RequiredFieldValidator_txtProductionDateAdjudicated_Planned control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredFieldValidator_txtProductionDateAdjudicated_Planned As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''ReqValidatorCalloutExtender_txtProductionDateAdjudicated_Planned control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ReqValidatorCalloutExtender_txtProductionDateAdjudicated_Planned As Global.AjaxControlToolkit.ValidatorCalloutExtender

    '''<summary>
    '''maskedEditExtender_txtProductionDateAdjudicated_Planned control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents maskedEditExtender_txtProductionDateAdjudicated_Planned As Global.AjaxControlToolkit.MaskedEditExtender

    '''<summary>
    '''RegularExpressionValidator_txtProductionDateAdjudicated_Planned control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RegularExpressionValidator_txtProductionDateAdjudicated_Planned As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''ValidatorCalloutExtender_txtProductionDateAdjudicated_Planned control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ValidatorCalloutExtender_txtProductionDateAdjudicated_Planned As Global.AjaxControlToolkit.ValidatorCalloutExtender

    '''<summary>
    '''ddlFoundAdvertisement control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlFoundAdvertisement As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''RequiredFieldValidator_ddlFoundAdvertisement control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredFieldValidator_ddlFoundAdvertisement As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''ValidatorCalloutExtender_ddlFoundAdvertisement control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ValidatorCalloutExtender_ddlFoundAdvertisement As Global.AjaxControlToolkit.ValidatorCalloutExtender

    '''<summary>
    '''txtAdjudicatorAttendanceComment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAdjudicatorAttendanceComment As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ibtn_NextStart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtn_NextStart As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''pnlBallotInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlBallotInfo As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''CollapsiblePanelExtender_ScoringCriteria control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CollapsiblePanelExtender_ScoringCriteria As Global.AjaxControlToolkit.CollapsiblePanelExtender

    '''<summary>
    '''pnlScoringCriteria_Title control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlScoringCriteria_Title As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''imgArrows_ScoringCriteria control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgArrows_ScoringCriteria As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''lblScoringCriteria_title control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScoringCriteria_title As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnlScoringCriteria control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlScoringCriteria As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblScoringCriteria control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScoringCriteria As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCategoryName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCategoryName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNomineeName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNomineeName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtScore control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtScore As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RequiredFieldValidator_Score control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredFieldValidator_Score As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''ValidatorCalloutExtender_Score control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ValidatorCalloutExtender_Score As Global.AjaxControlToolkit.ValidatorCalloutExtender

    '''<summary>
    '''RegularExpressionValidator_ScoreNum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RegularExpressionValidator_ScoreNum As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''ValidatorCalloutExtender_ScoreNum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ValidatorCalloutExtender_ScoreNum As Global.AjaxControlToolkit.ValidatorCalloutExtender

    '''<summary>
    '''txtScore_Calculated_For_Production control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtScore_Calculated_For_Production As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''MyAccordion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MyAccordion As Global.AjaxControlToolkit.Accordion

    '''<summary>
    '''Label1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblMatrixAdjectives control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMatrixAdjectives As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtComment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtComment As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RequiredFieldValidator_txtComment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredFieldValidator_txtComment As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''ValidatorCalloutExtender_txtComment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ValidatorCalloutExtender_txtComment As Global.AjaxControlToolkit.ValidatorCalloutExtender

    '''<summary>
    '''ibtnComment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtnComment As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''pnlNextPreviousButtons control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlNextPreviousButtons As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''ibtn_Previous control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtn_Previous As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''ibtn_SaveCurrent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtn_SaveCurrent As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''ibtn_Next control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtn_Next As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''lblSavedCurrent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSavedCurrent As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnlScoringSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlScoringSave As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblDaysToEditBallot control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDaysToEditBallot As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ibtn_Previous_ToSubmit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtn_Previous_ToSubmit As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''ibtn_SubmitBallot control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtn_SubmitBallot As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''chkSendSubmitEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkSendSubmitEmail As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblBallotToSubmit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBallotToSubmit As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnlResults control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlResults As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''btnMainMenu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnMainMenu As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblStatus As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSaveResults control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSaveResults As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnlErrors control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlErrors As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblErrors control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblErrors As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbtnCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtnCancel As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''Master property.
    '''</summary>
    '''<remarks>
    '''Auto-generated property.
    '''</remarks>
    Public Shadows ReadOnly Property Master() As Adjudication.MasterPageNoNav
        Get
            Return CType(MyBase.Master, Adjudication.MasterPageNoNav)
        End Get
    End Property
End Class
