'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class AdjudicatorComments

    '''<summary>
    '''lblErrors control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblErrors As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblStatus As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnlBallotInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlBallotInfo As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''txtPK_CompanyID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPK_CompanyID As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chkShowAll control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkShowAll As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''ddlProductionID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlProductionID As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCompanyName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCompanyName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblVenueName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblVenueName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblFirstPerformanceDateTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFirstPerformanceDateTime As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblLastPerformanceDateTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLastPerformanceDateTime As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnlUserData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlUserData As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblBestProduction control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBestProduction As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblProductionName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblProductionName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblBestProductionComment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBestProductionComment As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDirector control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDirector As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDirectorComment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDirectorComment As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblMusicalDirector control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMusicalDirector As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblMusicalDirectorComment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMusicalDirectorComment As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblChoreographer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblChoreographer As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblChoreographerComment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblChoreographerComment As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblScenicDesigner control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScenicDesigner As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblScenicDesignerComment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScenicDesignerComment As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblLightingDesigner control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLightingDesigner As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblLightingDesignerComment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLightingDesignerComment As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSoundDesigner control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSoundDesigner As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSoundDesignerComment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSoundDesignerComment As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCostumeDesigner control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCostumeDesigner As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCostumeDesignerComment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCostumeDesignerComment As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblOriginalPlaywright control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOriginalPlaywright As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblOriginalPlaywrightComment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOriginalPlaywrightComment As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblBestPerformer1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBestPerformer1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblBestPerformer1Comment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBestPerformer1Comment As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblBestPerformer2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBestPerformer2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblBestPerformer2Comment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBestPerformer2Comment As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblBestSupportingActor1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBestSupportingActor1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblBestSupportingActor1Comment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBestSupportingActor1Comment As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblBestSupportingActor2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBestSupportingActor2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblBestSupportingActor2Comment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBestSupportingActor2Comment As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblBestSupportingActress1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBestSupportingActress1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblBestSupportingActress1Comment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBestSupportingActress1Comment As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblBestSupportingActress2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBestSupportingActress2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblBestSupportingActress2Comment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBestSupportingActress2Comment As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAdjudicatorAttendance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAdjudicatorAttendance As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAdjudicatorAttendanceComment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAdjudicatorAttendanceComment As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnPrinterFriendly control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPrinterFriendly As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnEmailComments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnEmailComments As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Master property.
    '''</summary>
    '''<remarks>
    '''Auto-generated property.
    '''</remarks>
    Public Shadows ReadOnly Property Master() As Adjudication.MasterPage
        Get
            Return CType(MyBase.Master, Adjudication.MasterPage)
        End Get
    End Property
End Class
