'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class AdminAssignAdjudicators

    '''<summary>
    '''UpdatePanelMain control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanelMain As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''lblErrors control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblErrors As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSucessfulUpdate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSucessfulUpdate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnlGrid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlGrid As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''txtSortOrder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSortOrder As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtSortColumnName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSortColumnName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblTotalNumberOfRecords control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotalNumberOfRecords As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''gridMain control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gridMain As Global.System.Web.UI.WebControls.DataGrid

    '''<summary>
    '''pnlSelectedProductionDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlSelectedProductionDetail As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''txtPK_NominationID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPK_NominationID As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtFK_CompanyID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFK_CompanyID As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPK_ProductionID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPK_ProductionID As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtFullName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFullName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCompanyName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCompanyName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCompanyEmailAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCompanyEmailAddress As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''hlnkCompanyWebsite control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlnkCompanyWebsite As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''lblVenueName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblVenueName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAddress As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCity As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblState control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblState As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblZIP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblZIP As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''hlnkWebsite control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlnkWebsite As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''lblFirstPerformanceDateTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFirstPerformanceDateTime As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblLastPerformanceDateTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLastPerformanceDateTime As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTicketContactName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTicketContactName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTicketContactPhone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTicketContactPhone As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTicketContactEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTicketContactEmail As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnlAdjudictorList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlAdjudictorList As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lbtnAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtnAdd As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''gridSub control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gridSub As Global.System.Web.UI.WebControls.DataGrid

    '''<summary>
    '''pnlAddEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlAddEdit As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''txtPK_ScoringID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPK_ScoringID As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblTotalScore control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotalScore As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNumAdjudicatorsPerShow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNumAdjudicatorsPerShow As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblMaxShowsPerAdjudicator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMaxShowsPerAdjudicator As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblValidTrainingStartDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblValidTrainingStartDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlFK_CompanyID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlFK_CompanyID As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlPK_UserID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlPK_UserID As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''chkShowAssignmentCounts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkShowAssignmentCounts As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkIncludeBackupAdjudicators control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkIncludeBackupAdjudicators As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkShowAllAdjudicators control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkShowAllAdjudicators As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''ddlReserveAdjudicator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlReserveAdjudicator As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlPK_ScoringStatusID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlPK_ScoringStatusID As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtProductionDateAdjudicated_Planned control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtProductionDateAdjudicated_Planned As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtProductionDateAdjudicated_Actual control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtProductionDateAdjudicated_Actual As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlAdjudicatorRequestsReassignment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlAdjudicatorRequestsReassignment As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblLastUpdateByName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLastUpdateByName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblLastUpdateByDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLastUpdateByDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCreateByName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCreateByName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCreateByDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCreateByDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtAdminEmailComments_Assign control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAdminEmailComments_Assign As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rblEmailInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblEmailInfo As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''btnUpdate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnUpdate As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnCancelUpdate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancelUpdate As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''pnlDeleteConfirm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlDeleteConfirm As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblConfirmDelete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblConfirmDelete As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''rblEmailInfo_Delete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblEmailInfo_Delete As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''txtAdminEmailComments_Delete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAdminEmailComments_Delete As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnDeleteConfirm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDeleteConfirm As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnDeleteCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDeleteCancel As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Master property.
    '''</summary>
    '''<remarks>
    '''Auto-generated property.
    '''</remarks>
    Public Shadows ReadOnly Property Master() As Adjudication.MasterPage
        Get
            Return CType(MyBase.Master, Adjudication.MasterPage)
        End Get
    End Property
End Class
