'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Admin_WebsiteNotes

    '''<summary>
    '''lblErrors control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblErrors As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSucessfulUpdate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSucessfulUpdate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''hiddenPrimaryKeyID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hiddenPrimaryKeyID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''ibtnMainpageApplicationDesc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtnMainpageApplicationDesc As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''ftbMainpageApplicationDesc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ftbMainpageApplicationDesc As Global.FreeTextBoxControls.FreeTextBox

    '''<summary>
    '''ibtnMainpageApplicationNotes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtnMainpageApplicationNotes As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''ftbMainpageApplicationNotes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ftbMainpageApplicationNotes As Global.FreeTextBoxControls.FreeTextBox

    '''<summary>
    '''lblLastUpdateByName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLastUpdateByName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblLastUpdateByDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLastUpdateByDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnDEFAULTS_Update control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDEFAULTS_Update As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Master property.
    '''</summary>
    '''<remarks>
    '''Auto-generated property.
    '''</remarks>
    Public Shadows ReadOnly Property Master() As Adjudication.MasterPage
        Get
            Return CType(MyBase.Master, Adjudication.MasterPage)
        End Get
    End Property
End Class
