'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class BallotSummary

    '''<summary>
    '''pnlBallotInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlBallotInfo As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCompanyName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCompanyName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''hlnkCompanyEmailAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlnkCompanyEmailAddress As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''hlnkCompanyWebsite control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlnkCompanyWebsite As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''lblVenueName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblVenueName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAddress As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCity As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblState control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblState As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblZIP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblZIP As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''hlnkWebsite control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlnkWebsite As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''lblFirstPerformanceDateTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFirstPerformanceDateTime As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblLastPerformanceDateTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLastPerformanceDateTime As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTicketContactName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTicketContactName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTicketContactPhone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTicketContactPhone As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''hlnkTicketContactEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlnkTicketContactEmail As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''lblTicketPurchaseDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTicketPurchaseDetails As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnlUserData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlUserData As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblErrors control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblErrors As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSucessfulUpdate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSucessfulUpdate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPK_ScoringID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPK_ScoringID As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPK_NominationsID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPK_NominationsID As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtFK_CompanyID_Adjudicator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFK_CompanyID_Adjudicator As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtFK_UserID_Adjudicator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFK_UserID_Adjudicator As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCountOfNominations control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCountOfNominations As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtReserveAdjudicator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtReserveAdjudicator As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblFullname control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFullname As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtEmailPrimary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEmailPrimary As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtEmailSecondary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEmailSecondary As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblAdjudicatorCompany control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAdjudicatorCompany As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCompanyAdjudication control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCompanyAdjudication As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblLastUpdateByName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLastUpdateByName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblLastUpdateByDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLastUpdateByDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtAdjudicatorRequestsReassignmentNote control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAdjudicatorRequestsReassignmentNote As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblBallotSubmitDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBallotSubmitDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblProductionDateAdjudicated_Planned control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblProductionDateAdjudicated_Planned As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtProductionDateAdjudicated_Planned control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtProductionDateAdjudicated_Planned As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''CalendarExtender_txtProductionDateAdjudicated_Planned control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CalendarExtender_txtProductionDateAdjudicated_Planned As Global.AjaxControlToolkit.CalendarExtender

    '''<summary>
    '''imgCalendarIcon_txtProductionDateAdjudicated_Planned control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgCalendarIcon_txtProductionDateAdjudicated_Planned As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''RequiredFieldValidator_txtProductionDateAdjudicated_Planned control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredFieldValidator_txtProductionDateAdjudicated_Planned As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''ReqValidatorCalloutExtender_txtProductionDateAdjudicated_Planned control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ReqValidatorCalloutExtender_txtProductionDateAdjudicated_Planned As Global.AjaxControlToolkit.ValidatorCalloutExtender

    '''<summary>
    '''maskedEditExtender_txtProductionDateAdjudicated_Planned control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents maskedEditExtender_txtProductionDateAdjudicated_Planned As Global.AjaxControlToolkit.MaskedEditExtender

    '''<summary>
    '''RegularExpressionValidator_txtProductionDateAdjudicated_Planned control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RegularExpressionValidator_txtProductionDateAdjudicated_Planned As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''ValidatorCalloutExtender_txtProductionDateAdjudicated_Planned control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ValidatorCalloutExtender_txtProductionDateAdjudicated_Planned As Global.AjaxControlToolkit.ValidatorCalloutExtender

    '''<summary>
    '''txtProductionDateAdjudicated_Actual control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtProductionDateAdjudicated_Actual As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtAdjudicatorRequestsReassignment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAdjudicatorRequestsReassignment As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblFoundAdvertisement control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFoundAdvertisement As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlFoundAdvertisement control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlFoundAdvertisement As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''RequiredFieldValidator_ddlFoundAdvertisement control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredFieldValidator_ddlFoundAdvertisement As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''ValidatorCalloutExtender_ddlFoundAdvertisement control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ValidatorCalloutExtender_ddlFoundAdvertisement As Global.AjaxControlToolkit.ValidatorCalloutExtender

    '''<summary>
    '''lblAdjudicatorAttendanceCommentOptional control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAdjudicatorAttendanceCommentOptional As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAdjudicatorAttendanceComment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAdjudicatorAttendanceComment As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDirector control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDirector As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''DirectorScore control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DirectorScore As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblDirectorComment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDirectorComment As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblMusicalDirector control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMusicalDirector As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''MusicalDirectorScore control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MusicalDirectorScore As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblMusicalDirectorComment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMusicalDirectorComment As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblChoreographer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblChoreographer As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ChoreographerScore control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ChoreographerScore As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblChoreographerComment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblChoreographerComment As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblScenicDesigner control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScenicDesigner As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ScenicDesignerScore control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScenicDesignerScore As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblScenicDesignerComment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScenicDesignerComment As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblLightingDesigner control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLightingDesigner As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LightingDesignerScore control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LightingDesignerScore As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblLightingDesignerComment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLightingDesignerComment As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSoundDesigner control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSoundDesigner As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''SoundDesignerScore control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SoundDesignerScore As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblSoundDesignerComment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSoundDesignerComment As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCostumeDesigner control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCostumeDesigner As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''CostumeDesignerScore control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CostumeDesignerScore As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblCostumeDesignerComment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCostumeDesignerComment As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblOriginalPlaywright control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOriginalPlaywright As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''OriginalPlaywrightScore control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OriginalPlaywrightScore As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblOriginalPlaywrightComment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOriginalPlaywrightComment As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblBestPerformer1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBestPerformer1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''BestPerformer1Score control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BestPerformer1Score As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblBestPerformer1Comment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBestPerformer1Comment As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblBestPerformer2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBestPerformer2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''BestPerformer2Score control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BestPerformer2Score As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblBestPerformer2Comment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBestPerformer2Comment As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblBestSupportingActor1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBestSupportingActor1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''BestSupportingActor1Score control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BestSupportingActor1Score As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblBestSupportingActor1Comment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBestSupportingActor1Comment As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblBestSupportingActor2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBestSupportingActor2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''BestSupportingActor2Score control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BestSupportingActor2Score As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblBestSupportingActor2Comment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBestSupportingActor2Comment As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblBestSupportingActress1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBestSupportingActress1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''BestSupportingActress1Score control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BestSupportingActress1Score As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblBestSupportingActress1Comment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBestSupportingActress1Comment As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblBestSupportingActress2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBestSupportingActress2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''BestSupportingActress2Score control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BestSupportingActress2Score As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblBestSupportingActress2Comment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBestSupportingActress2Comment As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblBestProduction control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBestProduction As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''BestProductionScore control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BestProductionScore As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblBestProductionComment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBestProductionComment As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblError2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblError2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDaysToEditBallot control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDaysToEditBallot As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblScoringInstructions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScoringInstructions As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtScoringMinimum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtScoringMinimum As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtScoringMaximum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtScoringMaximum As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnPrinterFriendly control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPrinterFriendly As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnEmailMeThisBallot control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnEmailMeThisBallot As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''pnlResults control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlResults As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblStatus As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSaveResults control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSaveResults As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Master property.
    '''</summary>
    '''<remarks>
    '''Auto-generated property.
    '''</remarks>
    Public Shadows ReadOnly Property Master() As Adjudication.MasterPage
        Get
            Return CType(MyBase.Master, Adjudication.MasterPage)
        End Get
    End Property
End Class
