'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Ballot

    '''<summary>
    '''txtScore control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtScore As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Label1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblMatrixAdjectives control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMatrixAdjectives As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtComment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtComment As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''pnlScoringSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlScoringSave As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblDaysToEditBallot control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDaysToEditBallot As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ibtn_Previous_ToSubmit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtn_Previous_ToSubmit As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''ibtn_SubmitBallot control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtn_SubmitBallot As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''chkSendSubmitEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkSendSubmitEmail As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblBallotToSubmit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBallotToSubmit As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnlResults control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlResults As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''btnMainMenu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnMainMenu As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblStatus As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSaveResults control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSaveResults As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''UpdatePanel_Main control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel_Main As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''spnProductionName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spnProductionName As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''spnProducingCompanyName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spnProducingCompanyName As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblFullname control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFullname As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCompanyAdjudication control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCompanyAdjudication As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''spnProductionType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spnProductionType As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''spnProductionCategory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spnProductionCategory As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblFirstPerformanceDateTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFirstPerformanceDateTime As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblLastPerformanceDateTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLastPerformanceDateTime As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''spanTitle_CategoryName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spanTitle_CategoryName As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''spanTitle_NomineeName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spanTitle_NomineeName As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''divBallotDataEntry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divBallotDataEntry As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblCategoryName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCategoryName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblScoringCriteria control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScoringCriteria As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCatetoryName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCatetoryName As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''divNominee control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divNominee As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''span_Score control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents span_Score As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtScore_Calculated_For_Production control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtScore_Calculated_For_Production As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''span_Comment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents span_Comment As Global.System.Web.UI.HtmlControls.HtmlTextArea

    '''<summary>
    '''divCommonQuestions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divCommonQuestions As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblDaysToWaitForScoring control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDaysToWaitForScoring As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblMaxShowsPerAdjudicator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMaxShowsPerAdjudicator As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtProductionDateAdjudicated_Planned control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtProductionDateAdjudicated_Planned As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlFoundAdvertisement control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlFoundAdvertisement As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtAdjudicatorAttendanceComment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAdjudicatorAttendanceComment As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''spanFeedbackMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spanFeedbackMessage As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Master property.
    '''</summary>
    '''<remarks>
    '''Auto-generated property.
    '''</remarks>
    Public Shadows ReadOnly Property Master() As Adjudication.MasterPage
        Get
            Return CType(MyBase.Master, Adjudication.MasterPage)
        End Get
    End Property
End Class
