'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class MasterPage

    '''<summary>
    '''cphhead control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cphhead As Global.System.Web.UI.WebControls.ContentPlaceHolder

    '''<summary>
    '''FormSiteMaster control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FormSiteMaster As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''sm1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sm1 As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''navMenu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents navMenu As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''divMainMenu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divMainMenu As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''mnuAccount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mnuAccount As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''mnuAdjudicators control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mnuAdjudicators As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''mnuLiaisons control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mnuLiaisons As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''mnuEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mnuEmail As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''mnuAdministration control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mnuAdministration As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''mnuWebsiteSettings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mnuWebsiteSettings As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''divBallotMenu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divBallotMenu As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''ulNominatedCategories control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ulNominatedCategories As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''divPageTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divPageTitle As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblPageTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPageTitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''spnOverridesActive control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spnOverridesActive As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMessage As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cphBody control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cphBody As Global.System.Web.UI.WebControls.ContentPlaceHolder

    '''<summary>
    '''lblLoginID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLoginID As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblWebsiteLastBuildDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblWebsiteLastBuildDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''hdnTimeoutValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnTimeoutValue As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''hdnCurrentTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnCurrentTime As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''btnTimeOut control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnTimeOut As Global.System.Web.UI.WebControls.Button
End Class
