'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ScoringSummaryFinalists

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''lblErrors control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblErrors As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblProductionCategory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblProductionCategory As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSortOrder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSortOrder As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''grid_Production control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grid_Production As Global.System.Web.UI.WebControls.DataGrid

    '''<summary>
    '''grid_Director control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grid_Director As Global.System.Web.UI.WebControls.DataGrid

    '''<summary>
    '''grid_OriginalPlaywright control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grid_OriginalPlaywright As Global.System.Web.UI.WebControls.DataGrid

    '''<summary>
    '''grid_Actor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grid_Actor As Global.System.Web.UI.WebControls.DataGrid

    '''<summary>
    '''grid_Actress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grid_Actress As Global.System.Web.UI.WebControls.DataGrid

    '''<summary>
    '''grid_SupportingActor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grid_SupportingActor As Global.System.Web.UI.WebControls.DataGrid

    '''<summary>
    '''grid_SupportingActress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grid_SupportingActress As Global.System.Web.UI.WebControls.DataGrid

    '''<summary>
    '''grid_MusicalDirector control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grid_MusicalDirector As Global.System.Web.UI.WebControls.DataGrid

    '''<summary>
    '''grid_Choreographer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grid_Choreographer As Global.System.Web.UI.WebControls.DataGrid

    '''<summary>
    '''grid_CostumeDesigner control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grid_CostumeDesigner As Global.System.Web.UI.WebControls.DataGrid

    '''<summary>
    '''grid_ScenicDesigner control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grid_ScenicDesigner As Global.System.Web.UI.WebControls.DataGrid

    '''<summary>
    '''grid_SoundDesigner control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grid_SoundDesigner As Global.System.Web.UI.WebControls.DataGrid

    '''<summary>
    '''grid_LightingDesigner control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grid_LightingDesigner As Global.System.Web.UI.WebControls.DataGrid
End Class
